UPDATE `store_items` SET `unique_id` = 'skin_ninomiya_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/idolm@ster/ninomiya_asuka/ninomiya.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_neptune_adult' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/adult_neptune/normal/neptune.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_hatsumi_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/hatsumi_sega/normal/sega_girl.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_peter_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/misc/peter/peter_v2.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_noire_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/noire/normal/noire.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_yoshino_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/date_a_live/yoshino/spirit/yoshino.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_rikka_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/misc/rikka/rikka.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_brs_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/black_rock_shooter/brs/brs.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_amatsukaze_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/kantai_collection/amatsukaze/amatsukaze.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_kotori_lovelive' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/lovelive/kotori/school/kotori.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_hibiki_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/kantai_collection/hikibi/hikibi.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_haku_uniform' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/haku/uniform/haku.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_neptune_swimsuit' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/neptune/swimsuit/neptune.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_neptune_swimwear' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/neptune/swimwear/neptune.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_ram_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/re0/ram/ram.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_blanc_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/blanc/normal/blanc.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_vert_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/vert/normal/vert.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_inori_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/guilty_crown/inori_v2/inori.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_bananajoe_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/misc/banana_joe/banana_joe.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_tohka_spirit' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/date_a_live/tohka/spirit/tohka.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_kurumi_spirit' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/date_a_live/kurumi/spirit/kurumi.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_remilia_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/touhou/remilia_scarlet/remilia_scarlet.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_flandre_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/touhou/flandre_scarlet/flandre_scarlet.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_terminusest_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/seirei_tsukai_no_blade_dance/terminus_est/terminus_est.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_shimakaze_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/kantai_collection/shimakaze/shimakaze.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_kotori_school' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/date_a_live/kotori/school/kotori.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_seulbi_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/closeronline/seulbi/seulbi.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_rem_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/re0/rem/rem.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_uni_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/uni/normal/uni.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_miku_tda' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/hatsune_miku/tda/miku.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_miku_magnet' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/hatsune_miku/magnet/miku.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_u511_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/kantai_collection/U511/u511.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_kiana_moon' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/hongkai_impact3/kiana/kiana.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_neptune_nextform' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/neptune/nextform/nextpurple_nothruster.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_violet_cybernetic' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/closeronline/cybernetic/cybernetic.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_seulbi_queen' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/closeronline/violet/violet.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_momiji_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/touhou/momiji/momiji.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_hoppou_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/kantai_collection/hoppou/hoppou.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_histoire_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/histoire/normal/histoire.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_tiara_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/fairyfancyf/tiara/tiara.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_raynor_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/starcraft2/terran/raynor/raynor.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_luka_punk' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/luka/punk/luka.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_shino_ggo' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/sword_art_online/shino/ggo/shino.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_neptune_hdd' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/neptune/hdd/purpleheart.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_noire_nextform' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/noire/nextform/nextblack_nothruster.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_lty_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/luotianyi/canary/lty.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_yzl_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/yuezhengling/canary/yzl.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_pururut_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/pururut/normal/pururut.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_emilia_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/re0/emilia_v2/emilia.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_yuudachi_kai2' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/kantai_collection/yuudachi/yuudachi.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_haipa_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/haipa/haipa.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_kanzaki_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/idolm@ster/kanzaki_ranko/kanzaki.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_ia_tda' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/ia/ia.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_blanc_nextform' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/blanc/nextform/nextwhite_glow.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_ej_normal' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/misc/EnoshimaJunko/ej.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_kirito_sao' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/sword_art_online/kirito/sao/kirito.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_meiji_tda' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/utau/meiji/one_dress/meiji.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_luka_baka' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/luka/baka/luka.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_koroti_command' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/date_a_live/kotori/commander/kotori.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_kotori_spirit' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/date_a_live/kotori/spirit/kotori.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_million_swimwear' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/neptunia/Million_Arthur/swimwear/million.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_miku_cybertech' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/hatsune_miku/cybertech/miku_v2.mdl';
UPDATE `store_items` SET `unique_id` = 'skin_miku_nightmare' WHERE `type` = 'playerskin' AND `unique_id` = 'models/player/custom_player/maoling/vocaloid/hatsune_miku/nightmare/miku.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_kiana' WHERE `type` = 'hat' AND `unique_id` = 'models/maoling/wings/kiana/kiana_wings.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_01' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings01_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_03' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings03_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_04' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings04_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_05' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings05_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_06' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings06_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_07' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings07_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_08' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings08_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'wing_09' WHERE `type` = 'hat' AND `unique_id` = 'models/shop/perfectworld_wings09_v3.mdl';
UPDATE `store_items` SET `unique_id` = 'facemask_chicken' WHERE `type` = 'hat' AND `unique_id` = 'models/player/holiday/facemasks/facemask_chicken.mdl';
UPDATE `store_items` SET `unique_id` = 'facemask_pumpkin' WHERE `type` = 'hat' AND `unique_id` = 'models/player/holiday/facemasks/facemask_pumpkin.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_viking' WHERE `type` = 'hat' AND `unique_id` = 'models/vikinghelmet/vikinghelmet.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_antlers' WHERE `type` = 'hat' AND `unique_id` = 'models/sam/antlers.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_astronaut' WHERE `type` = 'hat' AND `unique_id` = 'models/astronauthelmet/astronauthelmet.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_fedora' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/fedorahat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_pimp' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/pimphat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_seuss' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/seusshat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_sombrero' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/sombrero.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_toeto' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/toetohat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_witch' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/witchhat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_afro' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/afro.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_catears' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/catears.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_top' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/tophat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_santa' WHERE `type` = 'hat' AND `unique_id` = 'models/player/holiday/santahat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_ktc' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/kfcbucket.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_pika' WHERE `type` = 'hat' AND `unique_id` = 'models/pikahat/pikahat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_animepatr' WHERE `type` = 'hat' AND `unique_id` = 'models/anime_patron/animepatr.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_dunce' WHERE `type` = 'hat' AND `unique_id` = 'models/duncehat/duncehat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_unclesam' WHERE `type` = 'hat' AND `unique_id` = 'models/store/hats/uncle_sam_hat.mdl';
UPDATE `store_items` SET `unique_id` = 'hat_daftpunk' WHERE `type` = 'hat' AND `unique_id` = 'models/store/hats/daft_punk_v1.mdl';
UPDATE `store_items` SET `unique_id` = 'glass_star' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/starglasses.mdl';
UPDATE `store_items` SET `unique_id` = 'glass_3d' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/3dglasses.mdl';
UPDATE `store_items` SET `unique_id` = 'glass_aviators' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/aviators.mdl';
UPDATE `store_items` SET `unique_id` = 'glass_kliener' WHERE `type` = 'hat' AND `unique_id` = 'models/gmod_tower/klienerglasses.mdl';
UPDATE `store_items` SET `unique_id` = 'shield_hylian' WHERE `type` = 'hat' AND `unique_id` = 'models/store/hats/hylian_shield.mdl';
UPDATE `store_items` SET `unique_id` = 'nadetrail_hongse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_hongse';
UPDATE `store_items` SET `unique_id` = 'nadetrail_ningmenglv', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_ningmenglv';
UPDATE `store_items` SET `unique_id` = 'nadetrail_lanse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_lanse';
UPDATE `store_items` SET `unique_id` = 'nadetrail_baixingse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_baixingse';
UPDATE `store_items` SET `unique_id` = 'nadetrail_shenfenhong', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_shenfenhong';
UPDATE `store_items` SET `unique_id` = 'nadetrail_shenhongse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_shenhongse';
UPDATE `store_items` SET `unique_id` = 'nadetrail_mise', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_mise';
UPDATE `store_items` SET `unique_id` = 'nadetrail_tuhaojin', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_tuhaojin';
UPDATE `store_items` SET `unique_id` = 'nadetrail_liangjuhuang', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_liangjuhuang';
UPDATE `store_items` SET `unique_id` = 'nadetrail_ziluolanhong', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_ziluolanhong';
UPDATE `store_items` SET `unique_id` = 'nadetrail_chengse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_chengse';
UPDATE `store_items` SET `unique_id` = 'nadetrail_cangqilinse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_cangqilinse';
UPDATE `store_items` SET `unique_id` = 'nadetrail_taorouse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_taorouse';
UPDATE `store_items` SET `unique_id` = 'nadetrail_zise', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_zise';
UPDATE `store_items` SET `unique_id` = 'nadetrail_qiaokelise', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_qiaokelise';
UPDATE `store_items` SET `unique_id` = 'nadetrail_shuiyase', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_shuiyase';
UPDATE `store_items` SET `unique_id` = 'nadetrail_jise', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_jise';
UPDATE `store_items` SET `unique_id` = 'nadetrail_shichejulanse', `type` = 'nadetrail' WHERE `type` = 'grenadetrail' AND `unique_id` = 'grenadetrail_laserbeam_shichejulanse';
UPDATE `store_items` SET `unique_id` = 'nademodel_henade_orange', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props/cs_italy/orange.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_flash_orange', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props/cs_italy/orange.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_smoke_orange', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props/cs_italy/orange.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_henade_banana', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props/cs_italy/bananna.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_flash_banana', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props/cs_italy/bananna.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_smoke_banana', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props/cs_italy/bananna.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_henade_waterlemon', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props_junk/watermelon01.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_flash_waterlemon', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props_junk/watermelon01.mdl';
UPDATE `store_items` SET `unique_id` = 'nademodel_smoke_waterlemon', `type` = 'nadeskin' WHERE `type` = 'grenadeskin' AND `unique_id` = 'models/props_junk/watermelon01.mdl';
UPDATE `store_items` SET `unique_id` = 'spray_cglogo_2' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/cglogo2.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_cglogo_1' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/cglogo.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_laia' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/laia.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_na' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/na.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_cghaipa' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/cghaipa.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_slaydog' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/slaydog.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_50highnoon' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/50highnoon.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_paomianwang' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/paomianwang.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_yaomeng' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/yaomeng1.vmt';
UPDATE `store_items` SET `unique_id` = 'spray_peter' WHERE `type` = 'spray' AND `unique_id` = 'materials/maoling/sprays/peter.vmt';
UPDATE `store_items` SET `unique_id` = 'sound_ow_genji' WHERE `type` = 'sound' AND `unique_id` = 'maoling/store/overwatch/genji.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_ow_hanzo' WHERE `type` = 'sound' AND `unique_id` = 'maoling/store/overwatch/hanzo.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_ow_junkrat' WHERE `type` = 'sound' AND `unique_id` = 'maoling/store/overwatch/junkrat.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_ow_mccree' WHERE `type` = 'sound' AND `unique_id` = 'maoling/store/overwatch/mccree.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_ow_mei' WHERE `type` = 'sound' AND `unique_id` = 'maoling/store/overwatch/mei.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_ow_lucio' WHERE `type` = 'sound' AND `unique_id` = 'maoling/store/overwatch/lucio.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_1' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_1.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_2' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_2.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_3' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_3.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_4' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_4.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_5' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_5.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_6' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_6.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_7' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_7.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_8' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_8.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_9' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_9.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_10' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_10.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_11' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_11.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_12' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_12.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_13' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_13.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_14' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_14.mp3';
UPDATE `store_items` SET `unique_id` = 'sound_cheer_15' WHERE `type` = 'sound' AND `unique_id` = 'cheer/cheer_15.mp3';
UPDATE `store_items` SET `unique_id` = 'weapon_knife_genji' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/overwatch/knife/genji/katana_v.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_bl2_zero' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/borderlands2/knife/zero/sword_v.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_knife_neptunia_4' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/neptunia/knife/neptune/sword_4_v.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_knife_neptunia_3' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/neptunia/knife/neptune/sword_3_v.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_knife_neptunia_2' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/neptunia/knife/neptune/sword_2_v.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_knife_neptunia_1' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/neptunia/knife/neptune/sword_1_v.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_knife_neptunia_nextpurple' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/neptunia/knife/neptune/nextpurple_sword_v.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_awp_neptune' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/neptunia/awp/neptune/awp.mdl';
UPDATE `store_items` SET `unique_id` = 'weapon_deagle_vocaloid' WHERE `type` = 'vwmodel ' AND `unique_id` = 'models/maoling/weapon/vocaloid/deagle/deagle.mdl';
UPDATE `store_items` SET `unique_id` = 'trail_planeptune' WHERE `type` = 'trail' AND `unique_id` = 'materials/maoling/trails/planeptune.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_huaji' WHERE `type` = 'trail' AND `unique_id` = 'materials/maoling/trails/huaji.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_doge' WHERE `type` = 'trail' AND `unique_id` = 'materials/maoling/trails/doge.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_arrowrainbow' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/arrowrainbow.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_awesome' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/awesome.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_banknote' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/banknote.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_bluelightning' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/bluelightning.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_crown' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/crown.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_fuul' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/fuu1.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_pokeball' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/pokeball.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_psychball' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/psychball.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_rainbow' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/rainbow.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_smugleaf' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/smugleaf.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_spongebob' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/spongebob.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_trollface' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/trollface.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_windows' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/windows.vmt';
UPDATE `store_items` SET `unique_id` = 'trail_yingyang' WHERE `type` = 'trail' AND `unique_id` = 'materials/sprites/store/trails/yingyang2.vmt';
UPDATE `store_items` SET `unique_id` = 'particle_01', `type` = 'particle'  WHERE `type` = 'Particles' AND `unique_id` = 'Trail';
UPDATE `store_items` SET `unique_id` = 'particle_05', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail5';
UPDATE `store_items` SET `unique_id` = 'particle_02', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail2';
UPDATE `store_items` SET `unique_id` = 'particle_03', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail3';
UPDATE `store_items` SET `unique_id` = 'particle_04', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail4';
UPDATE `store_items` SET `unique_id` = 'particle_07', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail7';
UPDATE `store_items` SET `unique_id` = 'particle_08', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail8';
UPDATE `store_items` SET `unique_id` = 'particle_09', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail9';
UPDATE `store_items` SET `unique_id` = 'particle_10', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail10';
UPDATE `store_items` SET `unique_id` = 'particle_11', `type` = 'particle' WHERE `type` = 'Particles' AND `unique_id` = 'Trail11';
UPDATE `store_items` SET `unique_id` = 'aura_01', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura1';
UPDATE `store_items` SET `unique_id` = 'aura_02', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura2';
UPDATE `store_items` SET `unique_id` = 'aura_03', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura3';
UPDATE `store_items` SET `unique_id` = 'aura_04', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura4';
UPDATE `store_items` SET `unique_id` = 'aura_05', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura5';
UPDATE `store_items` SET `unique_id` = 'aura_06', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura6';
UPDATE `store_items` SET `unique_id` = 'aura_07', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura7';
UPDATE `store_items` SET `unique_id` = 'aura_08', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura8';
UPDATE `store_items` SET `unique_id` = 'aura_09', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura9';
UPDATE `store_items` SET `unique_id` = 'aura_10', `type` = 'aura' WHERE `type` = 'Aura' AND `unique_id` = 'Aura10';
UPDATE `store_items` SET `unique_id` = 'neon_royalblue' WHERE `type` = 'neon' AND `unique_id` = '1';
UPDATE `store_items` SET `unique_id` = 'neon_apricot' WHERE `type` = 'neon' AND `unique_id` = '2';
UPDATE `store_items` SET `unique_id` = 'neon_blue' WHERE `type` = 'neon' AND `unique_id` = '3';
UPDATE `store_items` SET `unique_id` = 'neon_brown' WHERE `type` = 'neon' AND `unique_id` = '4';
UPDATE `store_items` SET `unique_id` = 'neon_cyan' WHERE `type` = 'neon' AND `unique_id` = '5';
UPDATE `store_items` SET `unique_id` = 'neon_darkblue' WHERE `type` = 'neon' AND `unique_id` = '6';
UPDATE `store_items` SET `unique_id` = 'neon_darkpink' WHERE `type` = 'neon' AND `unique_id` = '7';
UPDATE `store_items` SET `unique_id` = 'neon_darkred' WHERE `type` = 'neon' AND `unique_id` = '8';
UPDATE `store_items` SET `unique_id` = 'neon_darkgreen' WHERE `type` = 'neon' AND `unique_id` = '9';
UPDATE `store_items` SET `unique_id` = 'neon_beige' WHERE `type` = 'neon' AND `unique_id` = '10';
UPDATE `store_items` SET `unique_id` = 'neon_gold' WHERE `type` = 'neon' AND `unique_id` = '11';
UPDATE `store_items` SET `unique_id` = 'neon_green' WHERE `type` = 'neon' AND `unique_id` = '12';
UPDATE `store_items` SET `unique_id` = 'neon_lightpink' WHERE `type` = 'neon' AND `unique_id` = '13';
UPDATE `store_items` SET `unique_id` = 'neon_lightcyan' WHERE `type` = 'neon' AND `unique_id` = '14';
UPDATE `store_items` SET `unique_id` = 'neon_lightyellow' WHERE `type` = 'neon' AND `unique_id` = '15';
UPDATE `store_items` SET `unique_id` = 'neon_yellow' WHERE `type` = 'neon' AND `unique_id` = '16';
UPDATE `store_items` SET `unique_id` = 'neon_violetred' WHERE `type` = 'neon' AND `unique_id` = '17';
UPDATE `store_items` SET `unique_id` = 'neon_orange' WHERE `type` = 'neon' AND `unique_id` = '18';
UPDATE `store_items` SET `unique_id` = 'neon_cangyin' WHERE `type` = 'neon' AND `unique_id` = '19';
UPDATE `store_items` SET `unique_id` = 'neon_peach' WHERE `type` = 'neon' AND `unique_id` = '20';
UPDATE `store_items` SET `unique_id` = 'neon_purple' WHERE `type` = 'neon' AND `unique_id` = '21';
UPDATE `store_items` SET `unique_id` = 'neon_lightblue' WHERE `type` = 'neon' AND `unique_id` = '22';
UPDATE `store_items` SET `unique_id` = 'neon_chocolate' WHERE `type` = 'neon' AND `unique_id` = '23';
UPDATE `store_items` SET `unique_id` = 'neon_lightgreen' WHERE `type` = 'neon' AND `unique_id` = '24';
UPDATE `store_items` SET `unique_id` = 'neon_aquagreen' WHERE `type` = 'neon' AND `unique_id` = '25';
UPDATE `store_items` SET `unique_id` = 'neon_thistle' WHERE `type` = 'neon' AND `unique_id` = '26';
UPDATE `store_items` SET `unique_id` = 'neon_emerald' WHERE `type` = 'neon' AND `unique_id` = '27';
UPDATE `store_items` SET `unique_id` = 'neon_cornflowerblue' WHERE `type` = 'neon' AND `unique_id` = '28';
UPDATE `store_items` SET `unique_id` = 'neon_whitesmoke' WHERE `type` = 'neon' AND `unique_id` = '29';
UPDATE `store_items` SET `unique_id` = 'neon_violet' WHERE `type` = 'neon' AND `unique_id` = '30';
UPDATE `store_items` SET `unique_id` = 'nametag_144083262' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{purple}Princess{green}] ';
UPDATE `store_items` SET `unique_id` = 'nametag_0181409964' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{pink}Nokyo{green}] ';
UPDATE `store_items` SET `unique_id` = 'nametag_0103918523' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{yellow}马王{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_0166655872' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{lightblue}萌新出厂{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_0211984941' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{lightred}王子{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_098534074' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{green}蠢蛇{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_085922133' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{orange}歼星舰{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_1161803745' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{yellow}烂水果{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_1105159493' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{darkred}フラン{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_0104388155' WHERE `type` = 'nametag' AND `unique_id` = '{green}[{silver}玄学{green}]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_dsdf' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[东山大法]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_bjmd' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[比较萌的]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_3' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}_(:з」∠)_{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_dous' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}[抖S]{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_loli' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[萝莉]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_doum' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}[抖M]{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_xxs' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}[小学生]{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_demacia' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}[德玛西亚]{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_r18' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}[工口]{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_memeda' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}[么么哒]{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_bzkm' WHERE `type` = 'nametag' AND `unique_id` = '{lightblue}[本子狂魔]{teamcolor}';
UPDATE `store_items` SET `unique_id` = 'nametag_ge' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[大地球]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_wzs' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[我最帅]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_mint' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[薄荷味]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_bus' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[公交车]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_olddriver' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[老司机]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_hentai' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[HENTAI]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_ttt' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[TTT影帝]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_psybitch' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[新机表]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_friendlyfire' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[黑枪王子]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_rouge' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[暴动狂魔]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_runningman' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[跑男]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_saltyfish' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[咸鱼]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'nametag_routeidiot' WHERE `type` = 'nametag' AND `unique_id` = '{lightred}[路痴]{teamcolor} ';
UPDATE `store_items` SET `unique_id` = 'namecolor_rainbow' WHERE `type` = 'namecolor' AND `unique_id` = 'rainbow';
UPDATE `store_items` SET `unique_id` = 'namecolor_white' WHERE `type` = 'namecolor' AND `unique_id` = '{white}';
UPDATE `store_items` SET `unique_id` = 'namecolor_darkred' WHERE `type` = 'namecolor' AND `unique_id` = '{darkred}';
UPDATE `store_items` SET `unique_id` = 'namecolor_pink' WHERE `type` = 'namecolor' AND `unique_id` = '{pink}';
UPDATE `store_items` SET `unique_id` = 'namecolor_green' WHERE `type` = 'namecolor' AND `unique_id` = '{green}';
UPDATE `store_items` SET `unique_id` = 'namecolor_yellow' WHERE `type` = 'namecolor' AND `unique_id` = '{yellow}';
UPDATE `store_items` SET `unique_id` = 'namecolor_cyan' WHERE `type` = 'namecolor' AND `unique_id` = '{lime}';
UPDATE `store_items` SET `unique_id` = 'namecolor_lightred' WHERE `type` = 'namecolor' AND `unique_id` = '{lightred}';
UPDATE `store_items` SET `unique_id` = 'namecolor_grey' WHERE `type` = 'namecolor' AND `unique_id` = '{gray}';
UPDATE `store_items` SET `unique_id` = 'namecolor_olive' WHERE `type` = 'namecolor' AND `unique_id` = '{olive}';
UPDATE `store_items` SET `unique_id` = 'namecolor_orange' WHERE `type` = 'namecolor' AND `unique_id` = '{orange}';
UPDATE `store_items` SET `unique_id` = 'namecolor_sliver' WHERE `type` = 'namecolor' AND `unique_id` = '{silver}';
UPDATE `store_items` SET `unique_id` = 'namecolor_lightblue' WHERE `type` = 'namecolor' AND `unique_id` = '{lightblue}';
UPDATE `store_items` SET `unique_id` = 'namecolor_blue' WHERE `type` = 'namecolor' AND `unique_id` = '{blue}';
UPDATE `store_items` SET `unique_id` = 'namecolor_purple' WHERE `type` = 'namecolor' AND `unique_id` = '{purple}';
UPDATE `store_items` SET `unique_id` = 'namecolor_darkorange' WHERE `type` = 'namecolor' AND `unique_id` = '{darkorange}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_rainbow' WHERE `type` = 'msgcolor' AND `unique_id` = 'rainbow';
UPDATE `store_items` SET `unique_id` = 'msgcolor_white' WHERE `type` = 'msgcolor' AND `unique_id` = '{white}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_darkred' WHERE `type` = 'msgcolor' AND `unique_id` = '{darkred}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_pink' WHERE `type` = 'msgcolor' AND `unique_id` = '{pink}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_green' WHERE `type` = 'msgcolor' AND `unique_id` = '{green}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_yellow' WHERE `type` = 'msgcolor' AND `unique_id` = '{yellow}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_lime' WHERE `type` = 'msgcolor' AND `unique_id` = '{lime}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_lightred' WHERE `type` = 'msgcolor' AND `unique_id` = '{lightred}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_gray' WHERE `type` = 'msgcolor' AND `unique_id` = '{gray}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_olive' WHERE `type` = 'msgcolor' AND `unique_id` = '{olive}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_orange' WHERE `type` = 'msgcolor' AND `unique_id` = '{orange}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_sliver' WHERE `type` = 'msgcolor' AND `unique_id` = '{silver}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_lightblue' WHERE `type` = 'msgcolor' AND `unique_id` = '{lightblue}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_blue' WHERE `type` = 'msgcolor' AND `unique_id` = '{blue}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_purple' WHERE `type` = 'msgcolor' AND `unique_id` = '{purple}';
UPDATE `store_items` SET `unique_id` = 'msgcolor_darkorange' WHERE `type` = 'msgcolor' AND `unique_id` = '{darkorange}';
